
#ifndef PLANNING_COMMON_INCLUDE_PLANNING_COMMON_STATES_COMPLEX_STATE_SPACE_TYPES_H_
#define PLANNING_COMMON_INCLUDE_PLANNING_COMMON_STATES_COMPLEX_STATE_SPACE_TYPES_H_

#include "ompl/base/StateSpaceTypes.h"


enum StateSpaceType
{
  TANGENT_BUNDLE_SE2     =  ompl::base::STATE_SPACE_TYPE_COUNT + 1,

  XYZPSI_STATE_SPACE = 13,


};





#endif  // PLANNING_COMMON_INCLUDE_PLANNING_COMMON_STATES_COMPLEX_STATE_SPACE_TYPES_H_ 
